GET http://localhost:3000/

###

POST http://localhost:3000/students
Content-Type: application/json

{
    "first_name": "Samuel",
    "last_name": "Greenwald",
    "email": "sam@awesome-startup.com",
    "password": "ILikeP4p4y4s",
    "course": "5ed9f7b9976cf3cbe1623073"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "sam@awesome-startup.com",
    "password": "ILikeP4p4y4s"
}

###

GET http://localhost:3000/students
Authorization: Bearer 1234567

###

GET http://localhost:3000/students/5ed9707417d2d391638b5846

###

PUT http://localhost:3000/students
Content-Type: application/json

{
    "old_name": "Greenwald",
    "new_name": "Grünwald"
}

###

DELETE http://localhost:3000/students/5edf3cc87b05a43c96185f11

###


DELETE http://localhost:3000/students
Content-Type: application/json

{
    "condition": "first_name",
    "value": "Samuel"
}

###

POST http://localhost:3000/courses
Content-Type: application/json

{
    "course_name": "Web development bootcamp",
    "batch": "March 2020",
    "organization": "WBS"
}