GET http://localhost:3000/

###

POST http://localhost:3000/student
Content-Type: application/json

{
    "first_name": "Samuel",
    "last_name": "Greenwald"
}

###

GET http://localhost:3000/student

###

GET http://localhost:3000/student/5ed8aaa7606e4b97147e78

###

PUT http://localhost:3000/student
Content-Type: application/json

{
    "old_name": "Greenwald",
    "new_name": "Grünwald"
}

###

DELETE http://localhost:3000/student/5ed8aafb606e4b97147e746a

###


DELETE http://localhost:3000/student
Content-Type: application/json

{
    "condition": "first_name",
    "value": "Samuel"
}