GET http://localhost:3000/

###

POST http://localhost:3000/students
Content-Type: application/json

{
    "first_name": "Samuel",
    "last_name": "Greenwald",
    "course": "5ed9f7b9976cf3cbe1623073"
}

###

GET http://localhost:3000/students

###

GET http://localhost:3000/students/5ed9707417d2d391638b5846

###

PUT http://localhost:3000/students
Content-Type: application/json

{
    "old_name": "Greenwald",
    "new_name": "Grünwald"
}

###

DELETE http://localhost:3000/students/5ed9707417d2d391638b5846

###


DELETE http://localhost:3000/students
Content-Type: application/json

{
    "condition": "first_name",
    "value": "Samuel"
}

###

POST http://localhost:3000/courses
Content-Type: application/json

{
    "course_name": "Web development bootcamp",
    "batch": "March 2020",
    "organization": "WBS"
}